#語言(英語,繁體中文,簡體中文,巴西葡萄牙語,韓語)
#Language (English,Chinese_TW,Chinese_CN,Portuguese_BR,Korean_KR)
Language: English

#禁用裝備欄(原版的裝備欄將不能放裝備)
#Disable the equipment bar (the original equipment bar will not be able to put equipment)
Equipment: false